version: '3.8'

services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
    user: root

volumes:
  mssql-data: